export const ERROR_CODES = [
  "INVALID_REQUEST",
  "INVALID_VIDEO_REFERENCE",
  "UNSUPPORTED_VIDEO_FORMAT",
  "FILE_TOO_LARGE",
  "UPLOADCARE_FAILURE",
  "CLOUDINARY_FAILURE",
  "MAGIC_HOUR_AUTH_ERROR",
  "MAGIC_HOUR_INVALID_INPUT",
  "INSUFFICIENT_CREDITS",
  "MAGIC_HOUR_PROCESSING_FAILURE",
  "TRANSFORMATION_NOT_FOUND",
  "INVALID_WEBHOOK_SIGNATURE",
  "STALE_WEBHOOK",
  "OUTPUT_TRANSFER_FAILURE",
  "LONG_RUNNING_TRANSFORMATION",
  "INTERNAL_ERROR",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
